### ISSUE TITLE
Errors when building OIDC package from npm

### ISSUE THREAD

**Issue by Foxite** [Finastra/finastra-nodejs-libs#167]
```
$ npm install @finastra/nestjs-oidc
...
$ npm run build
...
node_modules/@finastra/nestjs-oidc/controllers/auth.controller.d.ts:1:23 - error TS2688: Cannot find type definition file for 'passport'.

1 /// <reference types="passport" />
                        ~~~~~~~~
node_modules/@finastra/nestjs-oidc/controllers/auth.controller.d.ts:9:24 - error TS2694: Namespace 'global.Express' has no exported member 'User'.

9     user(user: Express.User): UserInfo | UserinfoResponse;
```

**Comment by bcldvd** [comment]
Hey @Foxite, which version of Node and npm are you using ?

**Comment by Foxite** [comment]
I ended up using a different library and at some point, I discovered that I was using the wrong node/npm versions; I was using node 6.14 and the associated npm version, rather than npm 6.14. But I'm not totally sure if that would have been the problem.

So if you can't reproduce this on node LTS then I suppose this can be closed.

**Comment by bcldvd** [comment]
Our builds are running with Node LTS indeed (14.17.4 at time of writing).
Out of curiosity, which library did you end up using ?

**Comment by Foxite** [comment]
angular-auth-oidc-client
